name: CI
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    name: Lint (FE + BE)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Enable Corepack
        run: corepack enable
      - name: Use Yarn 1.x (classic)
        run: corepack prepare yarn@1.22.22 --activate
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run lint
        run: yarn lint

  test-backend:
    name: Test Backend (Jest)
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Enable Corepack
        run: corepack enable
      - name: Use Yarn 1.x (classic)
        run: corepack prepare yarn@1.22.22 --activate
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run backend unit tests
        run: yarn --cwd apps/backend test --ci --runInBand

  typecheck-frontend:
    name: Typecheck Frontend (TS)
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Enable Corepack
        run: corepack enable
      - name: Use Yarn 1.x (classic)
        run: corepack prepare yarn@1.22.22 --activate
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Type check
        run: yarn --cwd apps/frontend run tsc -b --pretty false

  e2e:
    name: Playwright E2E
    runs-on: ubuntu-latest
    needs: [lint, test-backend, typecheck-frontend]
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Enable Corepack
        run: corepack enable
      - name: Use Yarn 1.x (classic)
        run: corepack prepare yarn@1.22.22 --activate
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Seed database
        run: yarn --cwd apps/backend seed:dev
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: yarn test:e2e
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore


