name: Jira commit sync

on:
  push:

jobs:
  extract:
    runs-on: ubuntu-latest
    outputs:
      keys: ${{ steps.extract.outputs.keys }}
    steps:
      - name: Extract Jira keys from commits
        id: extract
        uses: actions/github-script@v7
        with:
          script: |
            const commits = context.payload.commits || [];
            const keys = new Set();
            for (const c of commits) {
              const text = `${c.message} ${c.id}`;
              const matches = text.match(/[A-Z][A-Z0-9]+-\d+/g) || [];
              matches.forEach(k => keys.add(k));
            }
            core.setOutput('keys', JSON.stringify(Array.from(keys)));
  comment:
    needs: extract
    if: ${{ needs.extract.outputs.keys != '[]' && needs.extract.outputs.keys != '' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        key: ${{ fromJSON(needs.extract.outputs.keys) }}
    steps:
      - name: Jira login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Comment commit link
        uses: atlassian/gajira-comment@v3
        with:
          issue: ${{ matrix.key }}
          comment: |
            Pushed to ${{ github.ref_name }} in ${{ github.repository }}
            Compare: ${{ github.event.compare }}

